on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
      - name: HubSpot CMS Deploy
        uses: HubSpot/hubspot-cms-deploy-action@v1.6
        with:
          src_dir: https://github.com/Maciek-Magician/flink_forward_website.git
          dest_dir: <src>
          portal_id: ${{ secrets.hubspot_portal_id }}
          personal_access_key: ${{ secrets.hubspot_personal_access_key }}
